version: "3.8"
services:
    reconcile:
        image: tarrciodev/rental-reconcile-api-v4
        container_name: rental-v0
        environment:
            - SPRING_DATASOURCE_URL={{}}
            - SPRING_DATASOURCE_USERNAME={{}}
            - SPRING_DATASOURCE_PASSWORD={{}}
            - N8N_WEBHOOK_URL={{}}
        ports:
            - "8080:8080"
        restart: always
