version: "3.8"
services:
    reconcile:
        image: simple-image
        container_name: simple
        environment:
            - N8N_WEBHOOK_URL=https://ninfra.tonile-angola.com/webhook-test/df0788b3-14b3-437c-a3bc-bb904fb81450
        ports:
            - "8080:8080"
        restart: always
